In [ ]:
import numpy as np

a=np.ones(4).reshape(2,2)
b=np.random.rand(2,2)
print(a)
print(b)
print(a*b)

[[1. 1.]
 [1. 1.]]
[[0.28916996 0.05204853]
 [0.23103874 0.62476218]]
[[0.28916996 0.05204853]
 [0.23103874 0.62476218]]


In [ ]:
!ls -al

total 16
drwxr-xr-x 1 root root 4096 Aug 13 13:35 .
drwxr-xr-x 1 root root 4096 Aug 24 05:29 ..
drwxr-xr-x 4 root root 4096 Aug 13 13:34 .config
drwxr-xr-x 1 root root 4096 Aug 13 13:35 sample_data


In [ ]:
!cat /etc/issue.net

Ubuntu 18.04.5 LTS


In [ ]:
!head /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
stepping	: 0
microcode	: 0x1
cpu MHz		: 2299.998
cache size	: 46080 KB
physical id	: 0


In [ ]:
!head -n 3 /proc/meminfo

MemTotal:       13302928 kB
MemFree:        10592224 kB
MemAvailable:   12524556 kB
